### ISSUE TITLE
您好, 请教一个问题: readme.md里 快捷键类似ctrl + B 包裹它的绿色小方块的样式怎么打出来呢?

### ISSUE THREAD

**Issue by huhaijing** [passwordgloo/Typora-foresee-theme#3]
您好, 在项目的readme.md中, 从第二张图片开始: use short cut Ctrl + B,   还有之后的Alt + Shift + 5, 这个包裹住快捷键单词Ctrl + B的绿色小方块 ,在typora中怎么打出来呢? 期待回复!

**Comment by passwordgloo** [comment]
使用HTML <kbd>标签包裹，例如<kbd>F5</kbd>，它的样式支持CSS自定义

**Comment by passwordgloo** [comment]
使用HTML标签`<kbd>`包裹想要突出的字符，来强调按键，例如
```html
<kbd>F5</kbd>
```
`<kbd>`支持CSS自定义样式
