### ISSUE TITLE
不知道使用那个文件

### ISSUE THREAD

**Issue by 0ddrs5** [passwordgloo/Typora-foresee-theme#6]
将那个文件放到themes文件里可以达到你的那种效果，我放了`source`文件下的文件到themes文件内但是下过很不理想

**Comment by passwordgloo** [comment]
# 如何使用本主题

## 下载

Git clone或者下载ZIP解压到Typora主题文件夹

国内用户使用[Gitee](https://gitee.com/passwordgloo/Typora-foresee-theme/repository/archive/study.zip)或者GitHub镜像网站


主题安装后，重启Typora在外观设置里可看到深色和浅色主题

## 自定义样式（可选）

编辑*_dark(light).css自定义样式文件，修改为自己喜欢的颜色、字体。

## 图标（可选）

主题提供本地和云端图标，调用本地图标时,拷贝badge文件夹到电脑固定位置，像插入图片一样绝对引用地址

## 渐变引用块（可选）

默认引用块是单色，但可修改为渐变色，具体参照仓库首页教程

**Comment by 0ddrs5** [comment]
ok懂了
